#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: "redisoperator.k8s.io/v1alpha1"
kind: SubmarineCluster
metadata:
  name: cluster-test
spec:
  additionalLabels:
    foo: bar
  numberOfMaster: 3
  replicationFactor: 1
  podTemplate:
    metadata:
      labels:
        app: cluster-test
    spec:
      ServiceAccountName: "redis-node"
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: redis
          image: "redisoperator/redisnode:latest"
          args: ["--v=6",
                 "--logtostderr=true",
                 "--alsologtostderr=true",
                 "--t=10s",
                 "--d=10s",
                 "--cluster-node-timeout=2000",
                 "--ns=$(POD_NAMESPACE)",
                 "--ip=$(POD_IP)",
                 "--rs=cluster-test"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name:  redis
            - containerPort: 16379
              name: cluster
          volumeMounts:
            - name: data
              mountPath: /redis-data
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
